// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

// 用户表
type User struct {
	// 用户 ID
	ID int64
	// 用户名
	Name string
	// 邮箱
	Email string
	// 创建时间
	CreatedAt time.Time
}
